server:
  port: 9009
  servlet:
    # 设置编码
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: tiny-job
  mvc:
    throw-exception-if-no-handler-found: true
  # 设置上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  # 设置jackson的默认时区和默认格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tiny-job?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123654
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # quartz配置信息
  quartz:
    job-store-type: jdbc
    scheduler-name: clusteredScheduler
    wait-for-jobs-to-complete-on-shutdown: true
    startup-delay: 1s
    overwrite-existing-jobs: true
    auto-startup: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
            skipUpdateCheck: true
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            maxMisfiresToHandleAtATime: 1
            misfireThreshold: 12000
            txIsolationLevelSerializable: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
            threadNamePrefix: quartz

# MyBatis-plus配置 映射xml文件
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 起别名
  type-aliases-package: com.csp.**.entity
  # 去除打印
  global-config:
    banner: false
  # 驼峰命名匹配
  configuration:
    map-underscore-to-camel-case: true
    # 设置在控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.tinycloud.tinyjob: info
    org.springframework: warn

tiny-security:
  # 存储类型，目前支持jdbc和redis和单机内存三种(redis,jdbc,single)
  store-type: jdbc
  # token名称 (同时也是cookie名称，适配前后端不分离的模式)
  token-name: token
  # token有效期 (即会话时长)，单位秒 默认1800秒
  timeout: 1800
  # token风格，uuid风格 (默认风格)，snowflake (纯数字风格)，objectid (变种uuid)，random128 (随机128位字符串)
  token-style: random128
  # 当配置为jdbc时，存储token的表名字，默认为b_auth_token
  table-name: t_auth_token

# springboot异步线程配置
async:
  executor:
    thread:
      core-pool-size: 5 #配置核心线程数
      keep-alive-seconds: 60 #设置线程活跃时间（秒）
      max-pool-size: 10 #配置最大线程数
      name-prefix: async-service- #配置线程池中的线程的名称前缀
      queue-capacity: 100 #配置队列大小